name = "meu-projeto-d1"
main = "worker.js"  # Define o arquivo principal do Worker
compatibility_date = "2024-02-22"



[[d1_databases]]
binding = "DB"
database_name = "process.env.DATABASE_NAME"
database_id = "process.env.D1_DATABASE_ID"



